title: "Junnan Li"
description: "My research focuses on 3D vision, neural rendering and inverse rendering."
url: "https://lijunnankman.github.io"
baseurl: ""

markdown: kramdown
plugins: []

exclude:
  - README.md
  - Publish.ps1
  - Publish.cmd
  - Preview.ps1
  - Preview.cmd
  - .gitignore
